package common.domain.title;

public enum TitleCode {
    POINTS_MORE_THAN_10K,
    EARLY_ARRIVAL_10_TIMES, LATE_ARRIVAL_5_TIMES, LATE_ARRIVAL_10_TIMES,
    BETTING_WINNING_5_TIMES, BETTING_LOSING_10_TIMES
}
